In [1]:
import pandas as pd

In [11]:
df=pd.read_csv("data\students.csv")

In [6]:
df.head(5)

  Student  Math  English  Science
0   Alice    78       85       90
1     Bob    65       70       72
2   Carol    92       88       95
3   David    55       60       58
4     Eve    81       79       84

In [7]:
df.shape

(5, 4)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  5 non-null      str
 1   Math     5 non-null      int64
 2   English  5 non-null      int64
 3   Science  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes

In [13]:
df.describe()

            Math    English    Science
count   5.000000   5.000000   5.000000
mean   74.200000  76.400000  79.800000
std    14.411801  11.458621  14.906374
min    55.000000  60.000000  58.000000
25%    65.000000  70.000000  72.000000
50%    78.000000  79.000000  84.000000
75%    81.000000  85.000000  90.000000
max    92.000000  88.000000  95.000000

In [14]:
df["Average"] = df[["Math","English","Science"]].mean(axis=1)

In [17]:
df.describe()

            Math    English    Science    Average
count   5.000000   5.000000   5.000000   5.000000
mean   74.200000  76.400000  79.800000  76.800000
std    14.411801  11.458621  14.906374  13.465181
min    55.000000  60.000000  58.000000  57.666667
25%    65.000000  70.000000  72.000000  69.000000
50%    78.000000  79.000000  84.000000  81.333333
75%    81.000000  85.000000  90.000000  84.333333
max    92.000000  88.000000  95.000000  91.666667

In [19]:
df.head(5)

  Student  Math  English  Science    Average
0   Alice    78       85       90  84.333333
1     Bob    65       70       72  69.000000
2   Carol    92       88       95  91.666667
3   David    55       60       58  57.666667
4     Eve    81       79       84  81.333333

In [23]:
highest = df["Average"].max()
df[df["Average"] == highest]

  Student  Math  English  Science    Average
2   Carol    92       88       95  91.666667

INSIGHTS:
Carol had the high est average hence she  was top of the  class

In [24]:
df.to_csv("data/students_analysis.csv", index=False)